server.port=8080
server.context-path=/

phoenix.enable= true
phoenix.url=jdbc:phoenix:192.168.2.114:2181;schema=OA
phoenix.type=com.alibaba.druid.pool.DruidDataSource
phoenix.driver-class-name=org.apache.phoenix.jdbc.PhoenixDriver
phoenix.username=
phoenix.password=
phoenix.default-auto-commit=true
phoenix.schema.isNamespaceMappingEnabled=true