
server: 
    port: 8080
    context-path: /

phoenix: 
  enable: true
  url: jdbc:phoenix:192.168.2.114:2181;schema=OA
  type: com.alibaba.druid.pool.DruidDataSource
  driver-class-name: org.apache.phoenix.jdbc.PhoenixDriver
  username: 
  password: 
  default-auto-commit: true
  schema: 
    isNamespaceMappingEnabled: true